### PR TITLE
Rmarkdown assignment

### PR DESCRIPTION
**Pull request by jebone**

### CODE REVIEW

**Comment by bbest** [comment]
Awesome! Love the map and data file. Can you please:
1.  Add your name to your Github user profile. I don't know who to give this grade to ;)
2. Add a little R chunk to read in your csv file and spit out a summary per the last part of step 3, [RMarkdown Assignment](http://ucsb-bren.github.io/env-info/wk02_program/#rmarkdown-assignment-%28individually%29).

Be sure to knit your Rmd to HTML, commit and push again to Github so I can see the changes.

Thanks @jebone!

**Comment by jebone** [comment]
Hi Ben,

Thanks for your feedback! I have added my name to the Github user profile. I’m slightly confused by your second point. I thought I had completed the R chunk part and placed it at the very bottom of the page. Is that not what you are referring to? 

I apologize for not coming to office hours for this. I unfortunately have meetings during that time.
Jen

**Comment by bbest** [comment]
Hi @jebone,

I don't think we're looking at the same [jebone.Rmd](https://raw.githubusercontent.com/jebone/env-info/gh-pages/students/jebone.Rmd), which does not have an R chunk in it. Have you done a Commit and Push on all your changes from RStudio?

Please also accept the pull request https://github.com/jebone/env-info/pull/1 to reflect preferred folders and username prefixes.

**Comment by jebone** [comment]
Hi Ben,

I have just tried resubmitting my jebone.Rmd file. Hopefully the chunk should be included in that version. Let me know if it isn’t there for some reason.

Thank you,
Jen

**Pull request merged**
