### PR TITLE
Week04 assignment

### PR DESCRIPTION
**Pull request by faundez**
Ben, please look at the end of my .Rmd document, I tried the dplyr elegance way, but it didn't work, could you help me on it?

### CODE REVIEW

**Comment by bbest** [comment]
What do you mean by "didn't work"? Can you please explain which line failed and what error message you got?

**Comment by faundez** [comment]
Below is the code: works well in the console but when I tried to knit give me this error:

Quitting from lines 345-352 (faundez.Rmd) 
Error in function_list[[k]](value) : could not find function "write_csv"
Calls: <Anonymous> ... eval -> _fseq -> freduce -> withVisible -> <Anonymous>
In addition: Warning message:
In native_encode(text) :
  some characters may not work under the current locale

Execution halted

# dplyr

e %T>%                                           # note tee operator %T>% for glimpse
  glimpse() %>%                                  # view data
  filter(year > 2013) %>%                        # limit rows
  arrange(desc(n)) %>%                           # descendant order
  filter(Country != c("World", "EU28")) %>%      # limit rows
  write_csv('data/co2_faundez.csv')              # write out csv
  head(co2_faundez)

You may find this code at the very end of my assignment and it's out of a chunk because I couldn't knit with it within a chunk

**Comment by bbest** [comment]
Hi @faundez,

Notice how the error message `Error in function_list[k] : could not find function "write_csv"` is very similar to the other problem you had with not finding the `read_excel` function. You have not loaded the library `readr` (`library(readr)`) which defines the `write_csv` function and possibly need to install the package first (`install.package('readr')`). Make sense?

**Comment by faundez** [comment]
Thanks Ben, I got it.

P

On Thu, Feb 11, 2016 at 3:57 PM, Ben Best notifications@github.com wrote:

> Hi @faundez https://github.com/faundez,
> 
> Notice how the error message Error in function_list[k] : could not find
> function "write_csv" is very similar to the other problem you had with
> not finding the read_excel function. You have not loaded the library readr
> (library(readr)) which defines the write_csv function and possibly need
> to install the package first (install.package('readr')). Make sense?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ucsb-bren/env-info/pull/121#issuecomment-183117510.

## 

Patricia Faundez Baez, PhD Student
BREN School of Environmental Science and Management
University of California, Santa Barbara, CA 93106
(805)453-3461
patriciafaundezbaez@gmail.com
http://www.laff.bren.ucsb.edu/laff-network/patricia-faúndez

**Pull request merged**
